version: '3.8'

services:
  odoo2:
    image: odoo:18
    container_name: odoo2
    labels:
      - traefik.enable=true
      - traefik.http.routers.odoo2.rule=Host(`odoo2.loxika.com`)
      - traefik.http.routers.odoo2.entrypoints=websecure
      - traefik.http.routers.odoo2.tls.certresolver=myresolver
      - traefik.http.services.odoo2.loadbalancer.server.port=8069
    ports:
      - "8071:8069"  # puerto diferente para acceso local
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./log:/var/log/odoo
      - odoo-web-data2:/var/lib/odoo
    environment:
      - HOST=db2
      - DATABASE=postgres
      - USER=odoo
      - PASSWORD=odoo
    depends_on:
      - db2
    networks:
      - traefik

  db2:
    image: postgres:15
    container_name: odoo2-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data2:/var/lib/postgresql/data/pgdata
    networks:
      - traefik

volumes:
  odoo-web-data2:
  odoo-db-data2:

networks:
  traefik:
    external: true